// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {main} from '../models';

export function AddTransferRecord(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function CancelTransfer():Promise<void>;

export function ClearHistory():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function GetSettings():Promise<settings.AppSettings>;

export function GetTransferHistory():Promise<Array<main.TransferRecord>>;

export function GetVersion():Promise<string>;

export function IsPaused():Promise<boolean>;

export function SaveSettings(arg1:settings.AppSettings):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectSaveDirectory():Promise<string>;

export function StartReceiver(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function StartSender(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<string>;
