// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTransferRecord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddTransferRecord'](arg1, arg2, arg3, arg4);
}

export function CancelTransfer() {
  return window['go']['main']['App']['CancelTransfer']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTransferHistory() {
  return window['go']['main']['App']['GetTransferHistory']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsPaused() {
  return window['go']['main']['App']['IsPaused']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectSaveDirectory() {
  return window['go']['main']['App']['SelectSaveDirectory']();
}

export function StartReceiver(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartReceiver'](arg1, arg2, arg3);
}

export function StartSender(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartSender'](arg1, arg2, arg3, arg4);
}
